// <auto-generated />
namespace StockDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TestM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestM));
        
        string IMigrationMetadata.Id
        {
            get { return "201905311954386_TestM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
